"use client"
import { HackerBackground } from '../ui/hackerbg';
import { useEffect, useState } from 'react';
import { TextComponent } from '../ui/featurefour';
import { cn } from '../lib/utils';

const data = [
  {
    title: "AcuDocx – Healthcare Document Portal",
    content:
      "A secure, HIPAA-compliant platform for managing patient documents and physician approvals.",
    did: "What we did: Full-stack development, dashboard design, role-based access, and real-time tracking.",
    srcImage:
      "https://res.cloudinary.com/eldoraui/image/upload/v1734107781/Screenshot_2024-12-13_at_10.06.08_PM_molet1.png",
  },
  {
    title: "HireLoop – Job Board + Applicant Tracking System",
    content:
      "A responsive job board with multi-role dashboards for candidates, clients, and admins.",
    did: "What we did: UX design, Laravel integration, email workflows, and admin analytics.",
    srcImage:
      "https://res.cloudinary.com/eldoraui/image/upload/v1734107781/Screenshot_2024-12-13_at_10.06.08_PM_molet1.png",
  },
  {
    title: "NexusGPT – AI-Powered Coaching Assistant",
    content:
      "A custom AI tool that helps professionals generate personalized coaching plans.",
    did: "What we did: OpenAI integration, prompt engineering, front-end UI in React, and user onboarding flow.",
    srcImage:
      "https://res.cloudinary.com/eldoraui/image/upload/v1734107781/Screenshot_2024-12-13_at_10.06.08_PM_molet1.png",
  },
  {
    title: "Copy and paste the code",
    content:
      "Copy and paste the code generated by the Cuicui library into your project and enjoy modern, ready-to-use components.",
    srcImage:
      "https://res.cloudinary.com/eldoraui/image/upload/v1734107781/Screenshot_2024-12-13_at_10.06.08_PM_molet1.png",
  },
];

export const Portfolios = () => {
  const [featureOpen, setFeatureOpen] = useState<number>(0);
  const [timer, setTimer] = useState<number>(0);
  useEffect(() => {
    const interval = setInterval(() => {
      setTimer((prev) => prev + 10);
    }, 10);
    return () => clearInterval(interval);
  }, []);
 
  useEffect(() => {
    if (timer > 10000) {
      setFeatureOpen((prev) => (prev + 1) % data.length);
      setTimer(0);
    }
  }, [timer]);

  return (
    <div className="relative w-full overflow-hidden bg-background container px-4 sm:px-20 py-10">
      <HackerBackground />
      <div className="container relative bg-white rounded-2xl">
        <div className="mb-16 text-center pt-8">
          <h2 className="text-3xl font-semibold tracking-tighter text-neutral-800 dark:text-neutral-300">
            Featured Projects
          </h2>
        </div>
        <div className=" grid grid-cols-1 gap-4 md:grid-cols-2">
          <div className="space-y-6">
            {data.map((item, index) => (
              <button
                className="w-full"
                key={item.title}
                onClick={() => {
                  setFeatureOpen(index);
                  setTimer(0);
                }}
                type="button"
              >
                <TextComponent
                  content={item.content}
                  did={item.did}
                  isOpen={featureOpen === index}
                  loadingWidthPercent={featureOpen === index ? timer / 100 : 0}
                  number={index + 1}
                  title={item.title}
                />
              </button>
            ))}
          </div>
          <div className="h-full">
            <div
              className={cn(
                "relative h-96 w-full overflow-hidden rounded-lg md:h-[500px]",
              )}
            >
              {data.map((item, index) => (
                <img
                  alt={item.title}
                  className={cn(
                    "absolute h-[500px] w-full transform-gpu rounded-lg object-cover transition-all duration-300",
                    featureOpen === index ? "scale-100" : "scale-70",
                    featureOpen > index ? "translate-y-full" : "",
                  )}
                  key={item.title}
                  src={item.srcImage}
                  style={{ zIndex: data.length - index }}
                />
              ))}
            </div>
          </div>
        </div>
      </div>
    </div>
  )
};
